apiVersion: apps/v1
kind: Deployment
metadata:
  name: counting-deployment
  labels:
    app: counting
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: counting
  template:
    metadata:
      labels:
        app: counting
    spec:
      containers:
      - name: counting
        {{DOCKER}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8001
        resources:
          limits:
            cpu: "{{CPU_L}}m"
          requests:
            cpu: "{{CPU_R}}m"
        env:
          - name: MODULE_NAME
            value: "counting"
          - name: LC_ALL
            value: "C.UTF-8"
          - name: LANG
            value: "C.UTF-8"
---
apiVersion: v1
kind: Service
metadata:
  name: counting-service
spec:
  selector:
    app: counting
  # type: LoadBalancer
  # externalIPs:
  # - 192.168.0.13
  ports:
    - port : 8001
