apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder-deployment
  labels:
    app: decoder
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: decoder
  template:
    metadata:
      labels:
        app: decoder
    spec:
      # nodeName: worker03
      containers:
      - name: decoder
        {{DOCKER}}
        imagePullPolicy: Always
        ports:
          - containerPort: 1935
          - containerPort: 5057
          - containerPort: 8090
          - containerPort: 6379
        resources:
          limits:
            cpu: "{{CPU_L}}m"
          requests:
            cpu: "{{CPU_R}}m"
        env:
          - name: MODULE_NAME
            value: "decoder"
          - name: LC_ALL
            value: "C.UTF-8"
          - name: LANG
            value: "C.UTF-8"
---
apiVersion: v1
kind: Service
metadata:
  name: decoder-service
spec:
  selector:
    app: decoder
  # type: LoadBalancer
  externalIPs:
  - 192.168.0.10
  ports:
    - name: port1
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: port2
      protocol: TCP
      port: 5057
      targetPort: 5057
    - name: port3
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: port4
      protocol: TCP
      port: 6379
      targetPort: 6379
