apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector-deployment
  labels:
    app: detector
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector
    spec:
      #nodeName: worker03
      containers:
      - name: detector
        {{DOCKER}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8001
        startupProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8001
        resources:
          limits:
            # nvidia.com/gpu: 1 # requesting 1 GPU
            cpu: "{{CPU_L}}m"
          requests:
            cpu: "{{CPU_R}}m"
        env:
          - name: MODULE_NAME
            value: "detector"
          - name: LC_ALL
            value: "C.UTF-8"
          - name: LANG
            value: "C.UTF-8"
---
apiVersion: v1
kind: Service
metadata:
  name: detector-service
spec:
  selector:
    app: detector
  type: LoadBalancer
  externalIPs:
  - 192.168.0.12
  ports:
    - port : 8001
---
#apiVersion: autoscaling/v2beta2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: detector-hpa
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: detector-deployment
#  behavior:
#    scaleDown:
#      stabilizationWindowSeconds: 60
#      policies:
#      - type: Percent
#        value: 50
#       periodSeconds: 30
#  minReplicas: 1
#  maxReplicas: 3
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 50

