apiVersion: apps/v1
kind: Deployment
metadata:
  name: resize-deployment
  labels:
    app: resize
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: resize
  template:
    metadata:
      labels:
        app: resize
    spec:
      containers:
      - name: resize
        {{DOCKER}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8001
        startupProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8001
        resources:
          limits:
            cpu: "{{CPU_L}}m"
          requests:
            cpu: "{{CPU_R}}m"
        env:
          - name: MODULE_NAME
            value: "resize"
          - name: LC_ALL
            value: "C.UTF-8"
          - name: LANG
            value: "C.UTF-8"
---
apiVersion: v1
kind: Service
metadata:
  name: resize-service
spec:
  selector:
    app: resize
  type: LoadBalancer
  externalIPs:
  - 192.168.0.11
  ports:
    - port : 8001
---
#apiVersion: autoscaling/v2beta2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: resize-hpa
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: resize-deployment
#  behavior:
#    scaleDown:
#      stabilizationWindowSeconds: 60
#      policies:
#      - type: Percent
#        value: 50
#        periodSeconds: 30
#  minReplicas: 1
#  maxReplicas: 5
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 25
---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: resize-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: resize-deployment
#   minReplicas: 3
#   maxReplicas: 10
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 20
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: AverageValue
#         averageValue: 100Mi
#   - type: Pods
#     pods:
#       metric:
#         name: packets_per_second
#       target:
#         type: AverageValue
#         averageValue: 10


